export const SOCKET_TRIGGER_CONNECT = "SOCKET_TRIGGER_CONNECT";
export const SOCKET_SET_ERROR = "SOCKET_SET_ERROR";
export const SOCKET_CONNECT = "SOCKET_CONNECT";
export const SOCKET_TRIGGER_DISCONNECT = "SOCKET_TRIGGER_DISCONNECT";
export const SOCKET_SET_LOADING = "SOCKET_SET_LOADING";
export const SOCKET_EMIT = "SOCKET_EMIT";

export const UPDATE_GAME_SESSION_STATE = 'UPDATE_GAME_SESSION_STATE';

export const SET_CURRENT_SCREEN = 'SET_CURRENT_SCREEN';
