export const SOCKET_TRIGGER_CONNECT = "SOCKET_TRIGGER_CONNECT";
export const SOCKET_CONNECT_ERROR = "SOCKET_CONNECT_ERROR";
export const SOCKET_ERROR = "SOCKET_ERROR";
export const SOCKET_TIMEOUT = "SOCKET_TIMEOUT";
export const SOCKET_CONNECT = "SOCKET_CONNECT";
export const SOCKET_DISCONNECT = "SOCKET_DISCONNECT";
export const SOCKET_TRIGGER_DISCONNECT = "SOCKET_TRIGGER_DISCONNECT";

export const FETCH_STUFF = 'FETCH_STUFF';
export const RECEIVE_STUFF = 'RECEIVE_STUFF';
export const ADD_TO_COUNT = 'ADD_TO_COUNT';
