export const SOCKET_TRIGGER_CONNECT = "SOCKET_TRIGGER_CONNECT";
export const SOCKET_SET_ERROR = "SOCKET_SET_ERROR";
export const SOCKET_CONNECT = "SOCKET_CONNECT";
export const SOCKET_TRIGGER_DISCONNECT = "SOCKET_TRIGGER_DISCONNECT";
export const SOCKET_SET_LOADING = "SOCKET_SET_LOADING";
export const SOCKET_EMIT = "SOCKET_EMIT";

export const FETCH_STUFF = 'FETCH_STUFF';
export const RECEIVE_STUFF = 'RECEIVE_STUFF';
export const ADD_TO_COUNT = 'ADD_TO_COUNT';
